import React from 'react';
import styles from './Policy.module.css';

export default function PrivacyPolicy() {
  return (
    <div className={styles.policyContainer}>
      <h1>Privacy Policy</h1>
      <p>This Privacy Policy is in continuation of the Term and Conditions on our Platform (as defined below) and shall be read with the same. Please note that all the capitalized terms used in this Policy (as defined herein-below) and not defined here shall have the same meaning as ascribed to it in Terms and Conditions.</p>

      <p>M/S. STRATNOVA TECHNOLOGIES, a private company incorporated under provisions of the Companies Act 2013 (“Vidhi AI”, “We”, “Us” or “Our”) is a pioneering cloud-based web platform that enables their customers (“Clients”, “You”, “Your” or “User”) to services as provided in our Terms and Conditions. These Services are made available to you through our website which shall be inclusive of any other website, as well as media channel, mobile website or mobile application related, linked or other connected thereto, which is owned by us (“Platform”).</p>

      <p>This Privacy Policy (“Policy”) outlines our practices and policies, the kinds of information we may collect from you when you access or use the Platform, the reasons for and methods for collection, use and disclose the information we gather from you for your use of the Platform, as well as security practises and procedures for safeguarding your privacy in relation to information shared with us. You agree to be bound by the terms and conditions of this Policy by accessing and using the Platform, which will be deemed to create a legal contract between you and Vidhi AI.</p>

      <p>This Policy must also be read in conjunction with and construed in accordance with all applicable laws of the country from which you access and use the Platform, including the provisions of the EU General Data Protection Regulation, the (Indian) Information Technology Act, 2000 ("IT Act"), and other similar laws as recognised in your jurisdiction. This Policy is officially recognised as an electronic contract between Vidhi AI and you.</p>

      <p>We reserve the right to amend, change or update this Policy to our discretion. You agree to be bound by any updated policies with your continued access and/or use of our Platform and subsequently our Services after any such changes have been duly notified in any form to you. Any such changes to the policy will be notified to your registered email address with us. We recommend you update your details with your active and correct email address for smooth communication. We will not be liable in case the registered email is inactive, incorrect or not updated for any claims regarding and not limited to communication gaps, liabilities and legal claims with regard to this policy.</p>

      <h2>Definitions</h2>
      <p>In compliance with jurisdictional compliances, we have listed an exhaustive list of information repeatedly defined and referenced in this policy.</p>
      <ol>
        <li>The term "Account" shall have the same meaning as has been provided under the Terms and Conditions.</li>
        <li>"Non-personal Identification Information" shall include but is not limited to browser name, the type of computer and technical information about your means of connection to the Platform such as the operating system, the Internet service providers utilized and other similar information used in conjecture with the access or use of the Platform and subsequently the Services available thereof.</li>
        <li>“Personal Identification Information” shall include such information which shall be voluntarily shared by you, in any format whereby such information shall be deemed to ascertain a person’s identity, or can be reasonably ascertained, from the information or opinion including, but not limited to, when you visit the Platform and conduct any such activity whereby you shall share be required to share such information, regardless of whether the information provided is true or not. Further, it shall be inclusive of but not limited to the information such as name, email address, phone number, and residential address disclosed by you pursuant to creation of an Account, use or access of the Platform and further the Services. In the event that you do not consent to share your Personal Identification Information with us, then you shall be freely allowed to do so, but it may prevent us from providing complete and full access and/or use of the Platform and the services thereof.</li>
        <li>"Sensitive personal data or information"/"SPDI" shall mean to include information relating to you, which directly or indirectly, is capable of identifying you including but not limited to: (i) credentials for use of the Platform; (ii) financial information; (iii) physical, physiological and mental health condition; (iv) sexual orientation; (v) medical records and history; (vi) any biometric information; and (vii) any other information which is considered as a sensitive personal data or information under the applicable law in your state.</li>
        <li>Non-personal Identification Information, Personal Identification Information and SPDI shall together be referred to as "Information".</li>
        <li>"Third Party" shall refer to any party other than you and Vidhi AI.</li>
      </ol>

      <h2>Information Collected</h2>
      <p>For the access and/or use of the Services, we have listed a list of the information we shall collect from you:</p>
      <ul>
        <li><strong>Information that you voluntarily provide us:</strong> This will include all the information that you provide us when access and/or using the Platform, which will include but shall not be limited to information you might provide us for the creation of your Account, additional Information providing during and/or for the provision of Services.</li>
        <li><strong>Information collected from Third-Party Sites:</strong> You may also register for an Account using your existing Instagram, Facebook or Gmail or similar Third Party accounts and log-in credentials (your "Third-Party Site Account"). As part of the functionality of the Platform, you may link your Account with Third Party Site Accounts, by either: (i) providing your Third Party Site Account login information to us through the Platform or (ii) allowing us to access your Third Party Site Account, as is permitted under the applicable terms and conditions that govern your use of each Third Party Site Account. It shall be your responsibility to read and update yourself with the policies of Third Party Site Account from time to time.</li>
        <li><strong>Cookie Policy:</strong> A cookie is a tiny bit of data that a web server stores on a web browser to read it later from that browser. Cookies help the browser remember information that is unique to a particular user. No information that can be used to identify you personally is stored in the cookies. Our cookies aid in extending the functionality of the website and aid in more precise usage analysis. Every time you visit our Platform, we'll check your browser to see if our cookies—which save details like whether you've previously visited the Platform and your preferences for it—are there. You may set your internet browser to reject cookies or to notify you when cookies are being used if you'd prefer not to receive them. However, turning off cookies will prevent the great bulk of our Platform from working, and making your browser "warn" you when cookies are used will make you less likely to use our Platform. Vidhi AI does not provide third party access to any cookie and do not disclose information from cookies to third parties except the information previously listed.</li>
        <li><strong>Sensitive Personal Data or Information (“SPDI”):</strong> For the sake of accuracy in providing services on the Platform, you may additionally be asked to reveal or affirm certain SPDI, including but not limited to specifics of your health condition or medical history, etc. Depending on how you engage with the Platform, different types of Information may be gathered from you. The Company promises to protect the information you supply while adhering to reasonable security policies and procedures and any relevant privacy laws.</li>
      </ul>

      <p>The following is the data that may be collected from you based upon your usage and access to the Platform:</p>
        <ul>
            <li><strong>Aggregated Data:</strong> The Company may perform research on its customers' demographics, interests, locations, and usage patterns of the Services based on the Personal Data and other information submitted to us in a continuing attempt to better understand and serve Users of the Services. We may aggregate this research and use it for any reason, including distributing the results to our affiliates, agents, and business partners. Your personal information is not contained in this aggregate data. To describe our services to existing and potential business partners as well as to other third parties for other legitimate objectives, we may also divulge aggregated user statistics.</li>
            <li><strong>Device and Usage Information:</strong> While you use the Service, we might gather data about your device. Device type, device family, operating system, carrier, unique device id, time zones, browser type, version, and language are some examples of this data. We might keep track of the things you do when using the Service. These details may include the date and time of logins, the features used or visited, latitude, longitude, and searches conducted through the Service.</li>
            <li><strong>Push Notifications:</strong> In relation to your Account or the Platform, we might ask to send you push notifications. You can disable these communications in your device's settings if you prefer not to receive them.</li>
            <li><strong>Verification of Information:</strong> We at certain times require you to provide additional information for confirmation of your identity for the access to your own Information as previously may have been provided to us. Upon the exercise of the right remove any and all information provided to us by you, we shall ask for additional information for verification purposes.</li>
        </ul>

      <h2>Use of Personal Data and Other Collected Information</h2>
      <p>Vidhi AI adheres to this Policy while using the Personal Data you supply. If you give us personal information for a particular reason, we will use it in connection with that particular reason. For instance, if you email us, we'll use the Personal Data you send to get back to you and see if we can't fix the issue.</p>
      <p>Other than as described above, we will notify you when we wish to provide Information about you to any Third Parties and give you the opportunity to choose not to share that Information. You have the option to allow or deny us to share such Information with a Third-Party, but in event, you deny us such permission, we might not be able to provide the full extent of our Services. It shall be your responsibility to keep us updated and duly informed of any change in email for the receipt of any information as mentioned herein for the purpose of consent.</p>

      <h2>Disclosure of Collected Information</h2>
      <p>Vidhi AI hereby represents that it does not sell or involve itself in businesses related to selling information. The company assures you that such disclosure is encrypted to avoid access and leaks and is acceptable under all data privacy and protection laws worldwide. The exceptions are listed as follows:</p>
      <ul>
        <li><strong>Business Transfers:</strong> Your Personal Data and other information may be shared in the diligence process with counterparties and others assisting with the transaction and transferred to a successor or affiliate as part of that transaction. Personal Data may be included in the transferred assets in the event of a corporate sale, merger, reorganisation, dissolution, or another similar event.</li>
        <li><strong>Service Requirements:</strong> In order to create personalised insights about you based on astrological positions on a regular basis (referred to as "Personal Readings") the Company may use your Personal Data. Your username and profile photo will be included in your Personal Readings and Compatibility Readings, but your gender, date of birth, or place of birth will not be disclosed. The AI service will have access to all your personal information as previously defined, and will have access to your answers for the best results. Such information will not be disclosed in any way.</li>
        <li><strong>Requirement under applicable law:</strong> The Information may be disclosed to any person, if such disclosure is required for a lawful purpose connected with a function or activity of Platform. The Personal Information may be disclosed, where the disclosure is necessary for compliance of a legal obligation under applicable law.</li>
      </ul>

      {/* ... Add other sections like Security, Exclusions, Links to Third Parties etc. here ... */}

      <h2>Grievance Redressal</h2>
      <p>Grievances in relation to this policy can be sent to our support team.</p>
      <p>Grievance letters can be mailed at contact@astroaura.ai.</p>

      <p>BY AGREEING TO THE TERMS OF THIS POLICY, YOU AGREE TO OUR PROCESSING OF YOUR PERSONAL INFORMATION FOR THE PURPOSES GIVEN HEREIN.</p>
    </div>
  );
}